//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        private double v1;
        private double v2;
        private int v3;
        private double v4;
        private int v5;
        private double v6;
        private int v7;
        private DateTime now;

        public Measurement(double v1, double v2, int v3, double v4, int v5, double v6, int v7, DateTime now)
        {
            this.v1 = v1;
            this.v2 = v2;
            this.v3 = v3;
            this.v4 = v4;
            this.v5 = v5;
            this.v6 = v6;
            this.v7 = v7;
            this.now = now;
        }

        public int MeasurementId { get; set; }
        public Nullable<decimal> OutsideTemperature { get; set; }
        public Nullable<decimal> OutsideHumidity { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<decimal> WindSpeed { get; set; }
        public Nullable<short> WindDir { get; set; }
        public Nullable<decimal> GustSpeed { get; set; }
        public Nullable<short> GustDir { get; set; }
        public Nullable<decimal> DewPoint { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual RainMeasurement RainMeasurement { get; set; }
    }
}
