//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RainMeasurement
    {
        public System.DateTime TimeStamp { get; set; }
        public decimal Rain { get; set; }
    
        public virtual Measurement Measurement { get; set; }
    }
}
